### PR TITLE
custom redirect at handleAuthCallback

### PR DESCRIPTION
**Pull request by devopsangel**
Cover case when during callback folks want to enable payment subscription.

### CODE REVIEW

**Review by ctrlaltdylan — CHANGES_REQUESTED** [review]
I like that it is backwards compatible with apps that are not using a dynamic URL to redirect to.

But before I merge I think it's worth documenting this option on the `README`. If you add a blurb about this feature there I think that would be very helpful to others and I'll merge and tag :)

**Comment by devopsangel** [comment]
> I like that it is backwards compatible with apps that are not using a dynamic URL to redirect to.
> 
> But before I merge I think it's worth documenting this option on the `README`. If you add a blurb about this feature there I think that would be very helpful to others and I'll merge and tag :)

Updated readme.

**Review by ctrlaltdylan — APPROVED** [review]

**Comment by devopsangel** [comment]
@ctrlaltdylan merge and tag?

**Comment by ctrlaltdylan** [comment]
@devopsangel I'm going to merge to master, but I will need to write a test to confirm the current API doesn't break with these changes.

**Pull request merged**
